### ISSUE TITLE
sn-user-service scope issues

### ISSUE THREAD

**Issue by usaaama2010** [YashchenkoN/social-network#10]
Hi @YashchenkoN ,

I was trying to get token with **UI** scope to create a user using **sn-user-service** from postman but it seems it is only supporting **server** scope, can you please tell if i want to create a user using a REST client or from any isolated frontend app (Angular is this case) then how i should access the oauth2 wrapped microservice?

**Comment by YashchenkoN** [comment]
You can use API after including Authorization header which can be created using the following pseudo function:
Authorization: Basic base64(sn-user-service:${SN_USER_SERVICE_PASSWORD})

**Comment by dev-one** [comment]
Great, Thanks

**Comment by dev-one** [comment]
@YashchenkoN - One more thing I would like to ask, I see 

> security.oauth2.client.ya-user-service={noop}

in application.properties of sn-auth-service

, what is it for and why we're using this?

**Comment by YashchenkoN** [comment]
@dev-one currently it's not used, but may be used in the future to authorize sn-user-service to call APIs of other services that are wrapped by oauth2

**Comment by dev-one** [comment]
Okay thanks
