### ISSUE TITLE
Not able to run the application

### ISSUE THREAD

**Issue by dev-one** [YashchenkoN/social-network#3]
Hi @YashchenkoN 

This project is awesome and thanks a lot for sharing this with the community. I'm getting into an issue when I try to run docker-compose up, you can see the error below:

> Pulling sn-discovery-service (social-network/sn-discovery-service:latest)...
> ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.
> 
> Continue with the new image? [yN]y
> Pulling sn-discovery-service (social-network/sn-discovery-service:latest)...
> ERROR: pull access denied for social-network/sn-discovery-service, repository does not exist or may require 'docker login'
> 

Can you please help me with this?

**Comment by YashchenkoN** [comment]
Hi @dev-one,

Thank you for opening this issue. Docker images of all microservices weren't published at public docker repo. That's why it shows you an error "repository does not exist".

You have to build all docker images manually by running the following script in your terminal:

```
sudo ./scripts/docker_all.sh
```

This script triggers Gradle job which builds docker images, tags them and publishes to the local docker repo.

After that, you can try to run `docker-compose` again. Feel free to contact me if it's still failing.

**Comment by YashchenkoN** [comment]
@dev-one accidentally closed this issues. Please, close if my advice will help you.

**Comment by YashchenkoN** [comment]
@dev-one please try to run
```
./gradlew clean build
```
firstly to build jar files and then execute ./docker_all.sh again

**Comment by dev-one** [comment]
@YashchenkoN The above command worked like a charm! Thanks for that. I'm getting another error on sn-auth-service, 

> 
> sn-auth-service_1       | ***************************
> sn-auth-service_1       | APPLICATION FAILED TO START
> sn-auth-service_1       | ***************************
> sn-auth-service_1       | 
> sn-auth-service_1       | Description:
> sn-auth-service_1       | 
> sn-auth-service_1       | Failed to bind properties under '' to com.zaxxer.hikari.HikariDataSource:
> sn-auth-service_1       | 
> sn-auth-service_1       |     Property: driverclassname
> sn-auth-service_1       |     Value: org.postgresql.Driver
> sn-auth-service_1       |     Origin: "driverClassName" from property source "source"
> sn-auth-service_1       |     Reason: Unable to set value for property driver-class-name
> sn-auth-service_1       | 
> sn-auth-service_1       | Action:
> sn-auth-service_1       | 
> sn-auth-service_1       | Update your application's configuration

**Comment by YashchenkoN** [comment]
@dev-one Oh, looks like the Postgres driver is missing. Fixing it right now.
My apologies for this. The project is under active development, so a lot of things are changing dynamically.

**Comment by YashchenkoN** [comment]
@dev-one In the future, I am going to add some kind of the end-to-end tests, so that master branch will be in the "bug-free" state

**Comment by YashchenkoN** [comment]
@dev-one fix has been merged to the master branch. Please pull the latest changes, rebuild artifacts using
```
./gradlew clean build
```
then
```
sudo ./scripts/docker_all.sh
```
After that, you should be able to run
```
./scripts/run_dev.sh
```

**Comment by dev-one** [comment]
@YashchenkoN Thanks a lot mate. It worked fine. It's great project please continue its development. There is one more issue, when I execute Gradle clean then it returns me an error that says 

> Unable to delete file: /social-network/sn-discovery-service/build/docker/Dockerfile

Docker file is read-only and it is marked as read-only after the build.

**Comment by YashchenkoN** [comment]
@dev-one it's because `docker_all.sh` was executed with `sudo`. Gradle docker plugin is not able to build images without `sudo`, so this is a kind of workaround.

Just execute `sudo ./gradlew clean` and it will remove all files even with read-only flag

**Comment by dev-one** [comment]
Thanks a lot @YashchenkoN . You're great.
